# Generated by Django 5.0.14 on 2026-07-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('introspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='connections.databaseconnection')),
                ('from_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_from', to='introspection.schemasnapshot')),
                ('to_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_to', to='introspection.schemasnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connection', '-created_at'], name='snapshots_s_connect_dbb2e6_idx')],
            },
        ),
    ]
