# Generated by Django 5.0.14 on 2026-07-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='user',
            name='lemonsqueezy_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
