# Generated by Django 5.0.14 on 2026-07-06 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_schema_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='connections.databaseconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('ai_explanation', models.TextField(blank=True)),
                ('row_count_estimate', models.BigIntegerField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='introspection.schemasnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('is_nullable', models.BooleanField()),
                ('is_foreign_key', models.BooleanField(default=False)),
                ('references_table', models.CharField(blank=True, max_length=255, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='introspection.tabledoc')),
            ],
        ),
        migrations.AddIndex(
            model_name='schemasnapshot',
            index=models.Index(fields=['connection', '-created_at'], name='introspecti_connect_12e6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tabledoc',
            index=models.Index(fields=['snapshot'], name='introspecti_snapsho_d700af_idx'),
        ),
    ]
